// Generated by posse for the Lead pane; rewritten on every Lead start.
// It keeps one `posse lookout` running. In lowkey mode the lookout quietly
// acknowledges safe routine Notices; actionable Notices enter model context
// without appearing in the User's conversation.
// @ts-nocheck

import { spawn } from "node:child_process";
import { Text } from "@earendil-works/pi-tui";
import { AssistantMessageComponent, ToolExecutionComponent } from "@earendil-works/pi-coding-agent";

const posse = "posse"; // POSSE_EXECUTABLE
const maxBackoffMs = 60_000;

// Pi has no per-session API for hiding transcript rows. Patch only the TUI
// presentation, not messages, tool execution, context, settings or session data.
// Keep the patch idempotent across extension reloads in the same Pi process.
const patchKey = Symbol.for("posse:lowkey-transcript-layout:v1");
function installLowkeyLayout() {
	const installed = globalThis[patchKey];
	if (installed) return installed;
	if (typeof AssistantMessageComponent !== "function" ||
		typeof AssistantMessageComponent.prototype.updateContent !== "function" ||
		typeof AssistantMessageComponent.prototype.setHiddenThinkingLabel !== "function" ||
		typeof ToolExecutionComponent !== "function" ||
		typeof ToolExecutionComponent.prototype.render !== "function") {
		throw new Error("Pi transcript components unavailable");
	}
	const state = { active: false, toolSeen: false };
	const updateContent = AssistantMessageComponent.prototype.updateContent;
	AssistantMessageComponent.prototype.updateContent = function (message, ...rest) {
		if (!state.active || !message?.content) return updateContent.call(this, message, ...rest);
		const toolStep = message.content.some((block) => block.type === "toolCall");
		// Before the first tool decision, text could still become a tool-step
		// preamble. Hold it until the message finishes. Once a tool has run,
		// the follow-up reply can stream normally.
		const awaitingDecision = rest[0] === true && !state.toolSeen;
		const presented = { ...message, content: message.content.filter((block) =>
			block.type !== "thinking" && !(block.type === "text" && (toolStep || awaitingDecision))) };
		const result = updateContent.call(this, presented, ...rest);
		this.lastMessage = message; // Invalidation must rebuild from the unfiltered message.
		return result;
	};
	const markExecutionStarted = ToolExecutionComponent.prototype.markExecutionStarted;
	ToolExecutionComponent.prototype.markExecutionStarted = function (...args) {
		state.toolSeen = true;
		return markExecutionStarted.apply(this, args);
	};
	const renderTool = ToolExecutionComponent.prototype.render;
	ToolExecutionComponent.prototype.render = function (...args) {
		return state.active ? [] : renderTool.apply(this, args);
	};
	globalThis[patchKey] = state;
	return state;
}

export default function (pi) {
	let layout;
	try { layout = installLowkeyLayout(); }
	catch (error) { console.error(`Posse lowkey: transcript presentation adapter unavailable, skipping. ${error}`); }
	let choiceRevision = 0;
	let ui;
	let lowkeyActive = false;
	let agentRunActive = false;
	let slabShown = false;
	const slabWidgetKey = "posse-lowkey-slab";
	const slabFrames = ["░░▒▓", "░▒▓█", "▒▓█▓", "▓█▓▒", "█▓▒░", "▓▒░░"];
	const slabIntervalMs = 225;
	const createSlabWidget = (tui) => {
		let frame = 0;
		let disposed = false;
		const animation = setInterval(() => {
			if (disposed) return;
			frame = (frame + 1) % slabFrames.length;
			tui.requestRender();
		}, slabIntervalMs);
		animation.unref?.();
		return {
			render: () => disposed ? [] : [slabFrames[frame]],
			invalidate: () => {},
			dispose: () => {
				if (disposed) return;
				disposed = true;
				clearInterval(animation);
			},
		};
	};
	const applySlabPresentation = (forceStockVisibility = false) => {
		if (!ui) return;
		const showSlab = lowkeyActive && agentRunActive;
		if (showSlab !== slabShown) {
			slabShown = showSlab;
			ui.setWidget(slabWidgetKey, showSlab ? (tui) => createSlabWidget(tui) : undefined, { placement: "aboveEditor" });
			ui.setWorkingVisible(!showSlab);
		} else if (forceStockVisibility && !showSlab) {
			ui.setWorkingVisible(true);
		}
	};
	const applyLowkey = (active) => {
		if (layout) layout.active = active;
		lowkeyActive = active;
		// Re-render assistant rows and request a TUI render for existing tool rows.
		// Undefined restores Pi's own label and hideThinkingBlock / Ctrl+T choice.
		ui?.setHiddenThinkingLabel(active ? "" : undefined);
		applySlabPresentation(!active);
	};
	const runLowkey = (args) => new Promise((resolve, reject) => {
		const command = spawn(posse, ["lowkey", ...args], { stdio: ["ignore", "pipe", "pipe"] });
		let stdout = "";
		let stderr = "";
		command.stdout.on("data", (chunk) => { stdout += chunk; });
		command.stderr.on("data", (chunk) => { stderr += chunk; });
		command.on("error", reject);
		command.on("close", (code) => {
			if (code !== 0) return reject(new Error(stderr.trim() || `posse lowkey exited ${code}`));
			const match = stdout.match(/^lowkey:\s*(on|off)\s*$/m);
			if (!match) return reject(new Error("posse lowkey returned no state"));
			resolve(match[1] === "on");
		});
	});
	const refreshLowkey = async () => {
		const revision = choiceRevision;
		try {
			const active = await runLowkey(["status"]);
			if (running && revision === choiceRevision) applyLowkey(active);
		} catch (error) {
			console.error(`Posse lowkey: cannot read current setting. ${error}`);
		}
	};
	pi.registerCommand("lowkey", {
		description: "Toggle or inspect the Lead's lowkey reporting and transcript presentation.",
		handler: async (args, ctx) => {
			const action = args.trim() || "toggle";
			if (!["toggle", "on", "off", "status"].includes(action)) {
				ctx.ui.notify("Usage: /lowkey [on|off|status]", "warning");
				return;
			}
			// Invalidate a lookout started before this command. Its snapshot can
			// finish after the write and must not restore an older presentation.
			choiceRevision++;
			try {
				let active;
				if (action === "toggle") active = !await runLowkey(["status"]);
				else if (action === "status") active = await runLowkey(["status"]);
				else active = action === "on";
				if (action !== "status") active = await runLowkey([active ? "on" : "off"]);
				choiceRevision++;
				applyLowkey(active);
				ctx.ui.notify(`lowkey ${active ? "on" : "off"}`, "info");
			} catch (error) {
				ctx.ui.notify(`lowkey unchanged: ${error}`, "error");
			}
		},
	});
	// Only custom messages sent by this extension have this type and trusted
	// origin details. A User typing the same header cannot impersonate one.
	pi.registerMessageRenderer("posse-notices", (message, { outputPad }, theme) => {
		const [header, quotedBody] = message.content.split("\nbody: ", 2);
		let body = quotedBody;
		try { body = JSON.parse(quotedBody); } catch {}
		return new Text(theme.fg("accent", header) + "\n" + String(body).split("\n").map((line) => "│ " + line).join("\n"), outputPad, 0);
	});
	let running = false;
	let child;
	let timer;
	let backoffMs = 1_000;
	let pendingRequeue;
	let pendingNotification = false;

	const notifyFailure = () => {
		try {
			pi.sendMessage({
				customType: "posse-notices",
				content: '[posse | Posse -> Lead project | delivery-error]\nbody: "Notice delivery failed. Run `posse` to inspect open Notices."',
				display: true,
				details: { origin: "posse", from: "Posse", to: "Lead", task: "project", type: "delivery-error" },
			}, { triggerTurn: true, deliverAs: "followUp" });
			pendingNotification = false;
		} catch {
			pendingNotification = true;
		}
	};

	const schedule = (delayMs) => {
		clearTimeout(timer);
		timer = setTimeout(watch, delayMs);
		timer.unref?.();
	};

	const watch = () => {
		if (!running || child) return;
		if (pendingNotification) notifyFailure();
		let output = "";
		const watchRevision = choiceRevision;
		const args = ["lookout", "--json", "--quiet-routine"];
		if (pendingRequeue) args.push("--requeue", pendingRequeue);
		const current = spawn(posse, args, { stdio: ["ignore", "pipe", "ignore"] });
		child = current;
		current.stdout.on("data", (chunk) => {
			output += chunk;
		});
		current.on("error", () => {});
		current.on("close", (code) => {
			if (child !== current) return;
			child = undefined;
			if (!running) return;
			let count = 0;
			let wake;
			let lowkey;
			let notices = [];
			let ids = [];
			if (code === 0) {
				pendingRequeue = undefined; // The requeue command succeeded.
				try {
					const result = JSON.parse(output);
					count = result.notices?.length ?? 0;
					wake = result.wake;
					lowkey = result.lowkey;
					if (typeof lowkey === "boolean" && watchRevision === choiceRevision) {
						choiceRevision++;
						applyLowkey(lowkey);
					}
					notices = result.notices ?? [];
					ids = notices.map((notice) => notice.id);
				} catch {
					// A malformed successful result may already have been marked
					// delivered. Wake the Lead to inspect all open Notices.
					notifyFailure();
				}
			}
			if (count > 0) {
				try {
					if (typeof wake !== "string" || !wake.startsWith("[posse | Posse -> Lead ")) throw new Error("invalid Notice envelope");
					const tasks = [...new Set(notices.map((notice) => /^t[1-9][0-9]*$/.test(notice.task) ? notice.task : "project"))];
					pi.sendMessage({
						customType: "posse-notices",
						content: wake,
						display: lowkey !== true,
						details: { origin: "posse", from: "Posse", to: "Lead", tasks, type: "notice", ids, notices },
					}, { triggerTurn: true, deliverAs: "followUp" });
				} catch {
					// The model never received this batch. Requeue precisely its ids,
					// including mixed batches, before the next lookout attempt.
					if (ids.length === count && ids.every((id) => Number.isSafeInteger(id) && id > 0)) {
						pendingRequeue = ids.join(",");
					} else {
						notifyFailure();
					}
					schedule(backoffMs);
					backoffMs = Math.min(backoffMs * 2, maxBackoffMs);
					return;
				}
				backoffMs = 1_000;
				schedule(0);
				return;
			}
			schedule(code === 0 ? 0 : backoffMs);
			if (code !== 0) backoffMs = Math.min(backoffMs * 2, maxBackoffMs);
		});
	};

	pi.on("agent_start", (_event, ctx) => {
		if (layout) layout.toolSeen = false;
		agentRunActive = true;
		ui = ctx.ui;
		applySlabPresentation();
	});

	pi.on("agent_settled", (_event, ctx) => {
		agentRunActive = false;
		ui = ctx.ui;
		applySlabPresentation(true);
	});

	pi.on("session_start", async (_event, ctx) => {
		ui = ctx.ui;
		agentRunActive = false;
		applySlabPresentation(true);
		running = true;
		await refreshLowkey();
		schedule(0);
	});

	pi.on("session_shutdown", async () => {
		agentRunActive = false;
		applySlabPresentation(true);
		running = false;
		ui = undefined;
		clearTimeout(timer);
		child?.kill();
		child = undefined;
	});
}
