// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Approval struct {
	ID        int64
	TaskID    int64
	Action    string
	UserQuote string
	At        int64
	BranchSha string
}

type ConfigApproval struct {
	ID        int64
	ProjectID int64
	Key       string
	Action    string
	Value     sql.NullString
	UserQuote string
	At        int64
}

type Decision struct {
	ID             int64
	ProjectID      int64
	TaskID         int64
	Origin         string
	Question       string
	OptionsJson    string
	Answer         string
	UserQuote      string
	CreatedAt      int64
	AnsweredAt     int64
	Kind           string
	TaskLaunches   int64
	ObsoleteAt     int64
	ObsoleteReason string
}

type DecisionNoticeCursor struct {
	ProjectID    int64
	LastNoticeID int64
}

type Event struct {
	ID         int64
	ReceivedAt int64
	Kind       string
	PaneID     string
	DataJson   string
}

type Intent struct {
	ID               int64
	ProjectID        int64
	TaskID           int64
	Command          string
	Step             string
	ProcessID        int64
	UpdatedAt        int64
	PayloadJson      string
	ProcessBootID    string
	ProcessStartTime string
}

type LeadStartClaim struct {
	ProjectID int64
	ClaimedAt int64
}

type Message struct {
	ID          int64
	TaskID      int64
	Body        string
	CreatedAt   int64
	DeliveredAt sql.NullInt64
	Status      string
	ClaimToken  string
	ClaimedAt   int64
	WaitForIdle int64
}

type Mount struct {
	ID         int64
	ProjectID  int64
	N          int64
	Path       string
	State      string
	TaskID     sql.NullInt64
	AcquiredAt int64
	ReleasedAt int64
}

type Notice struct {
	ID          int64
	ProjectID   int64
	TaskID      sql.NullInt64
	Kind        string
	Summary     string
	DataJson    string
	CreatedAt   int64
	DeliveredAt sql.NullInt64
	AckedAt     sql.NullInt64
	ClaimToken  string
	ClaimedAt   int64
}

type NoticeNotification struct {
	ProjectID  int64
	NotifiedAt int64
}

type PrObservation struct {
	ID          int64
	ProjectID   int64
	TaskID      int64
	PrUrl       string
	HeadSha     string
	State       string
	Checks      string
	Review      string
	Mergeable   string
	MergeCommit string
	ObservedAt  int64
	Repo        string
}

type Project struct {
	ID               int64
	Name             string
	Root             string
	DefaultBranch    string
	HerdrWorkspaceID string
	LeadPaneID       string
	LeadLabel        string
	LeadAbsentSince  int64
	Status           string
	CreatedAt        int64
	LastActivityAt   int64
	LeadLaunches     int64
	Kind             string
	DownAt           int64
}

type ProjectRepo struct {
	ID            int64
	ProjectID     int64
	Name          string
	Path          string
	DefaultBranch string
	Status        string
	CreatedAt     int64
	UpdatedAt     int64
}

type ProjectRuntime struct {
	ProjectID          int64
	ServerStartedAt    string
	RecoveryGeneration string
	RecoveryOwnerPid   int64
	RecoveryClaimedAt  int64
}

type ProjectWatchState struct {
	ProjectID             int64
	PrPolledAt            int64
	PrConsecutiveFailures int64
	CheckoutCheckedAt     int64
	RootBehindHead        string
	PrPollClaimUntil      int64
	PrPollClaimToken      string
}

type RepoWatchState struct {
	ProjectID      int64
	Repo           string
	RootBehindHead string
}

type Signal struct {
	ID       int64
	TaskID   int64
	Verb     string
	Note     string
	DataJson string
	At       int64
}

type Task struct {
	ID                   int64
	ProjectID            int64
	Seq                  int64
	Type                 string
	ReviewsTaskID        sql.NullInt64
	Title                string
	State                string
	Profile              string
	DispatchRule         string
	LandingMode          string
	AutonomyReview       string
	AutonomyLand         string
	Branch               string
	BaseRef              string
	WorktreePath         string
	HerdrWorkspaceID     string
	PaneID               string
	PaneLabel            string
	AgentName            string
	AgentSession         string
	PrUrl                string
	LandedRef            string
	LastOutputHash       string
	LastWorktreeHash     string
	LastProgressAt       int64
	AgentAbsentSince     int64
	CreatedAt            int64
	UpdatedAt            int64
	MountID              sql.NullInt64
	Launches             int64
	GatedSha             string
	AgentServerStartedAt string
	IdleSince            int64
	ShortName            string
}

type TaskRepo struct {
	ID           int64
	TaskID       int64
	Repo         string
	WorktreePath string
	BaseRef      string
	LandingMode  string
	State        string
	GatedSha     string
	PrUrl        string
	LandedRef    string
	UpdatedAt    int64
}

type Transition struct {
	ID        int64
	TaskID    int64
	FromState string
	ToState   string
	Source    string
	Note      string
	At        int64
}

type VerifiedPrHead struct {
	TaskID  int64
	PrUrl   string
	HeadSha string
}
