// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const ackAllNotices = `-- name: AckAllNotices :execresult
UPDATE notices SET acked_at = ? WHERE project_id = ? AND acked_at IS NULL
`

type AckAllNoticesParams struct {
	AckedAt   sql.NullInt64
	ProjectID int64
}

func (q *Queries) AckAllNotices(ctx context.Context, arg AckAllNoticesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, ackAllNotices, arg.AckedAt, arg.ProjectID)
}

const ackNotice = `-- name: AckNotice :execresult
UPDATE notices SET acked_at = ? WHERE id = ? AND project_id = ? AND acked_at IS NULL
`

type AckNoticeParams struct {
	AckedAt   sql.NullInt64
	ID        int64
	ProjectID int64
}

func (q *Queries) AckNotice(ctx context.Context, arg AckNoticeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, ackNotice, arg.AckedAt, arg.ID, arg.ProjectID)
}

const acquireIdleMount = `-- name: AcquireIdleMount :execresult
UPDATE mounts SET state = 'held', task_id = ?, acquired_at = ?, released_at = 0
WHERE mounts.id = (
  SELECT candidate.id FROM mounts candidate WHERE candidate.project_id = ? AND candidate.state = 'idle' ORDER BY candidate.n LIMIT 1
) AND mounts.state = 'idle'
`

type AcquireIdleMountParams struct {
	TaskID     sql.NullInt64
	AcquiredAt int64
	ProjectID  int64
}

func (q *Queries) AcquireIdleMount(ctx context.Context, arg AcquireIdleMountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acquireIdleMount, arg.TaskID, arg.AcquiredAt, arg.ProjectID)
}

const activeWorkerCount = `-- name: ActiveWorkerCount :one
SELECT COUNT(*) FROM tasks
WHERE project_id = ? AND state IN ('spawning', 'working', 'needs-decision', 'blocked', 'stalled')
`

func (q *Queries) ActiveWorkerCount(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeWorkerCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allTasks = `-- name: AllTasks :many
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks WHERE project_id = ? ORDER BY seq
`

func (q *Queries) AllTasks(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, allTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.ReviewsTaskID,
			&i.Title,
			&i.State,
			&i.Profile,
			&i.DispatchRule,
			&i.LandingMode,
			&i.AutonomyReview,
			&i.AutonomyLand,
			&i.Branch,
			&i.BaseRef,
			&i.WorktreePath,
			&i.HerdrWorkspaceID,
			&i.PaneID,
			&i.PaneLabel,
			&i.AgentName,
			&i.AgentSession,
			&i.PrUrl,
			&i.LandedRef,
			&i.LastOutputHash,
			&i.LastWorktreeHash,
			&i.LastProgressAt,
			&i.AgentAbsentSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MountID,
			&i.Launches,
			&i.GatedSha,
			&i.AgentServerStartedAt,
			&i.IdleSince,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allocateLeadLaunch = `-- name: AllocateLeadLaunch :one
UPDATE projects SET lead_launches = lead_launches + 1 WHERE id = ? RETURNING lead_launches
`

func (q *Queries) AllocateLeadLaunch(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocateLeadLaunch, id)
	var lead_launches int64
	err := row.Scan(&lead_launches)
	return lead_launches, err
}

const allocateTaskLaunch = `-- name: AllocateTaskLaunch :one
UPDATE tasks SET launches = launches + 1, updated_at = ? WHERE id = ? RETURNING launches
`

type AllocateTaskLaunchParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) AllocateTaskLaunch(ctx context.Context, arg AllocateTaskLaunchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocateTaskLaunch, arg.UpdatedAt, arg.ID)
	var launches int64
	err := row.Scan(&launches)
	return launches, err
}

const allocateTaskSequence = `-- name: AllocateTaskSequence :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM tasks WHERE project_id = ?
`

func (q *Queries) AllocateTaskSequence(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocateTaskSequence, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const bindPRBodyMarker = `-- name: BindPRBodyMarker :execresult
UPDATE pr_body_markers SET pr_url = ?, updated_at = ?
WHERE task_id = ? AND repo = ? AND marker_token = ? AND (pr_url = '' OR pr_url = ?)
`

type BindPRBodyMarkerParams struct {
	PrUrl       string
	UpdatedAt   int64
	TaskID      int64
	Repo        string
	MarkerToken string
	PrUrl_2     string
}

func (q *Queries) BindPRBodyMarker(ctx context.Context, arg BindPRBodyMarkerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, bindPRBodyMarker,
		arg.PrUrl,
		arg.UpdatedAt,
		arg.TaskID,
		arg.Repo,
		arg.MarkerToken,
		arg.PrUrl_2,
	)
}

const breakMount = `-- name: BreakMount :exec
UPDATE mounts SET state = 'broken', task_id = NULL, released_at = ? WHERE id = ?
`

type BreakMountParams struct {
	ReleasedAt int64
	ID         int64
}

func (q *Queries) BreakMount(ctx context.Context, arg BreakMountParams) error {
	_, err := q.db.ExecContext(ctx, breakMount, arg.ReleasedAt, arg.ID)
	return err
}

const clearDownProjectLead = `-- name: ClearDownProjectLead :exec
UPDATE projects SET lead_pane_id = '', lead_label = '', lead_absent_since = 0 WHERE id = ? AND down_at != 0
`

func (q *Queries) ClearDownProjectLead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearDownProjectLead, id)
	return err
}

const clearGatedSHALandingToDone = `-- name: ClearGatedSHALandingToDone :exec
UPDATE tasks SET gated_sha = '' WHERE id = ? AND state = 'done'
`

func (q *Queries) ClearGatedSHALandingToDone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearGatedSHALandingToDone, id)
	return err
}

const clearProjectLead = `-- name: ClearProjectLead :exec
UPDATE projects SET lead_pane_id = '', lead_label = '', lead_absent_since = 0, status = 'missing' WHERE id = ?
`

func (q *Queries) ClearProjectLead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearProjectLead, id)
	return err
}

const clearTaskGatedSHA = `-- name: ClearTaskGatedSHA :exec
UPDATE tasks SET gated_sha = '', updated_at = ? WHERE id = ? AND state = 'done'
`

type ClearTaskGatedSHAParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ClearTaskGatedSHA(ctx context.Context, arg ClearTaskGatedSHAParams) error {
	_, err := q.db.ExecContext(ctx, clearTaskGatedSHA, arg.UpdatedAt, arg.ID)
	return err
}

const clearWorkspaceToken = `-- name: ClearWorkspaceToken :exec
INSERT INTO notice_notifications(project_id, notified_at) VALUES (?, 0)
ON CONFLICT(project_id) DO UPDATE SET notified_at = 0
`

func (q *Queries) ClearWorkspaceToken(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, clearWorkspaceToken, projectID)
	return err
}

const countApproval = `-- name: CountApproval :one
SELECT COUNT(*) FROM approvals WHERE task_id = ? AND action = ?
`

type CountApprovalParams struct {
	TaskID int64
	Action string
}

func (q *Queries) CountApproval(ctx context.Context, arg CountApprovalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApproval, arg.TaskID, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMount = `-- name: DeleteMount :execresult
DELETE FROM mounts WHERE id = ? AND project_id = ? AND state IN ('idle', 'broken')
`

type DeleteMountParams struct {
	ID        int64
	ProjectID int64
}

func (q *Queries) DeleteMount(ctx context.Context, arg DeleteMountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMount, arg.ID, arg.ProjectID)
}

const insertApproval = `-- name: InsertApproval :exec
INSERT INTO approvals(task_id, action, user_quote, at)
VALUES (?, ?, ?, ?)
`

type InsertApprovalParams struct {
	TaskID    int64
	Action    string
	UserQuote string
	At        int64
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.ExecContext(ctx, insertApproval,
		arg.TaskID,
		arg.Action,
		arg.UserQuote,
		arg.At,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events(received_at, kind, pane_id, data_json) VALUES (?, ?, ?, ?)
`

type InsertEventParams struct {
	ReceivedAt int64
	Kind       string
	PaneID     string
	DataJson   string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ReceivedAt,
		arg.Kind,
		arg.PaneID,
		arg.DataJson,
	)
	return err
}

const insertLeadStartClaim = `-- name: InsertLeadStartClaim :execresult
INSERT INTO lead_start_claims(project_id, claimed_at) VALUES (?, ?)
ON CONFLICT(project_id) DO NOTHING
`

type InsertLeadStartClaimParams struct {
	ProjectID int64
	ClaimedAt int64
}

func (q *Queries) InsertLeadStartClaim(ctx context.Context, arg InsertLeadStartClaimParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertLeadStartClaim, arg.ProjectID, arg.ClaimedAt)
}

const insertMount = `-- name: InsertMount :execresult
INSERT INTO mounts(project_id, n, path, state, task_id, acquired_at, released_at)
VALUES (?, ?, ?, ?, ?, ?, 0)
`

type InsertMountParams struct {
	ProjectID  int64
	N          int64
	Path       string
	State      string
	TaskID     sql.NullInt64
	AcquiredAt int64
}

func (q *Queries) InsertMount(ctx context.Context, arg InsertMountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMount,
		arg.ProjectID,
		arg.N,
		arg.Path,
		arg.State,
		arg.TaskID,
		arg.AcquiredAt,
	)
}

const insertNotice = `-- name: InsertNotice :execresult
INSERT INTO notices(project_id, task_id, kind, summary, data_json, created_at, delivered_at, acked_at)
VALUES (?, ?, ?, ?, ?, ?, NULL, NULL)
`

type InsertNoticeParams struct {
	ProjectID int64
	TaskID    sql.NullInt64
	Kind      string
	Summary   string
	DataJson  string
	CreatedAt int64
}

func (q *Queries) InsertNotice(ctx context.Context, arg InsertNoticeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertNotice,
		arg.ProjectID,
		arg.TaskID,
		arg.Kind,
		arg.Summary,
		arg.DataJson,
		arg.CreatedAt,
	)
}

const insertProject = `-- name: InsertProject :execresult
INSERT INTO projects(name, root, default_branch, status, created_at, last_activity_at)
VALUES (?, ?, ?, 'active', ?, ?)
`

type InsertProjectParams struct {
	Name           string
	Root           string
	DefaultBranch  string
	CreatedAt      int64
	LastActivityAt int64
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProject,
		arg.Name,
		arg.Root,
		arg.DefaultBranch,
		arg.CreatedAt,
		arg.LastActivityAt,
	)
}

const insertSignal = `-- name: InsertSignal :execresult
INSERT INTO signals(task_id, verb, note, data_json, at) VALUES (?, ?, ?, ?, ?)
`

type InsertSignalParams struct {
	TaskID   int64
	Verb     string
	Note     string
	DataJson string
	At       int64
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSignal,
		arg.TaskID,
		arg.Verb,
		arg.Note,
		arg.DataJson,
		arg.At,
	)
}

const insertTask = `-- name: InsertTask :execresult
INSERT INTO tasks(
    project_id, seq, type, reviews_task_id, title, short_name, state, profile, dispatch_rule,
    landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path,
    herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url,
    landed_ref, last_output_hash, last_worktree_hash, last_progress_at,
    agent_absent_since, idle_since, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	ProjectID        int64
	Seq              int64
	Type             string
	ReviewsTaskID    sql.NullInt64
	Title            string
	ShortName        string
	State            string
	Profile          string
	DispatchRule     string
	LandingMode      string
	AutonomyReview   string
	AutonomyLand     string
	Branch           string
	BaseRef          string
	WorktreePath     string
	HerdrWorkspaceID string
	PaneID           string
	PaneLabel        string
	AgentName        string
	AgentSession     string
	PrUrl            string
	LandedRef        string
	LastOutputHash   string
	LastWorktreeHash string
	LastProgressAt   int64
	AgentAbsentSince int64
	IdleSince        int64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTask,
		arg.ProjectID,
		arg.Seq,
		arg.Type,
		arg.ReviewsTaskID,
		arg.Title,
		arg.ShortName,
		arg.State,
		arg.Profile,
		arg.DispatchRule,
		arg.LandingMode,
		arg.AutonomyReview,
		arg.AutonomyLand,
		arg.Branch,
		arg.BaseRef,
		arg.WorktreePath,
		arg.HerdrWorkspaceID,
		arg.PaneID,
		arg.PaneLabel,
		arg.AgentName,
		arg.AgentSession,
		arg.PrUrl,
		arg.LandedRef,
		arg.LastOutputHash,
		arg.LastWorktreeHash,
		arg.LastProgressAt,
		arg.AgentAbsentSince,
		arg.IdleSince,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertTransition = `-- name: InsertTransition :exec
INSERT INTO transitions(task_id, from_state, to_state, source, note, at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTransitionParams struct {
	TaskID    int64
	FromState string
	ToState   string
	Source    string
	Note      string
	At        int64
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransition,
		arg.TaskID,
		arg.FromState,
		arg.ToState,
		arg.Source,
		arg.Note,
		arg.At,
	)
	return err
}

const lastNoticeDelivery = `-- name: LastNoticeDelivery :one
SELECT CAST(COALESCE(MAX(delivered_at), 0) AS INTEGER) FROM notices WHERE project_id = ?
`

func (q *Queries) LastNoticeDelivery(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastNoticeDelivery, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const lastNoticeNotification = `-- name: LastNoticeNotification :one
SELECT CAST(COALESCE((SELECT notified_at FROM notice_notifications WHERE project_id = ?), 0) AS INTEGER)
`

func (q *Queries) LastNoticeNotification(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastNoticeNotification, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const liveTasks = `-- name: LiveTasks :many
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE project_id = ? AND state IN ('spawning', 'working', 'needs-decision', 'blocked', 'stalled', 'done', 'landing') ORDER BY seq
`

func (q *Queries) LiveTasks(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, liveTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.ReviewsTaskID,
			&i.Title,
			&i.State,
			&i.Profile,
			&i.DispatchRule,
			&i.LandingMode,
			&i.AutonomyReview,
			&i.AutonomyLand,
			&i.Branch,
			&i.BaseRef,
			&i.WorktreePath,
			&i.HerdrWorkspaceID,
			&i.PaneID,
			&i.PaneLabel,
			&i.AgentName,
			&i.AgentSession,
			&i.PrUrl,
			&i.LandedRef,
			&i.LastOutputHash,
			&i.LastWorktreeHash,
			&i.LastProgressAt,
			&i.AgentAbsentSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MountID,
			&i.Launches,
			&i.GatedSha,
			&i.AgentServerStartedAt,
			&i.IdleSince,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageDelivered = `-- name: MarkMessageDelivered :exec
UPDATE messages SET status = 'delivered', delivered_at = ? WHERE id = ? AND status = 'queued'
`

type MarkMessageDeliveredParams struct {
	DeliveredAt sql.NullInt64
	ID          int64
}

func (q *Queries) MarkMessageDelivered(ctx context.Context, arg MarkMessageDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markMessageDelivered, arg.DeliveredAt, arg.ID)
	return err
}

const markNoticeDelivered = `-- name: MarkNoticeDelivered :exec
UPDATE notices SET delivered_at = ?
WHERE id = ? AND project_id = ? AND delivered_at IS NULL AND acked_at IS NULL
`

type MarkNoticeDeliveredParams struct {
	DeliveredAt sql.NullInt64
	ID          int64
	ProjectID   int64
}

func (q *Queries) MarkNoticeDelivered(ctx context.Context, arg MarkNoticeDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markNoticeDelivered, arg.DeliveredAt, arg.ID, arg.ProjectID)
	return err
}

const markProjectDown = `-- name: MarkProjectDown :exec
UPDATE projects SET down_at = ? WHERE id = ?
`

type MarkProjectDownParams struct {
	DownAt int64
	ID     int64
}

func (q *Queries) MarkProjectDown(ctx context.Context, arg MarkProjectDownParams) error {
	_, err := q.db.ExecContext(ctx, markProjectDown, arg.DownAt, arg.ID)
	return err
}

const mountByTask = `-- name: MountByTask :one
SELECT id, project_id, n, path, state, task_id, acquired_at, released_at FROM mounts WHERE task_id = ?
`

func (q *Queries) MountByTask(ctx context.Context, taskID sql.NullInt64) (Mount, error) {
	row := q.db.QueryRowContext(ctx, mountByTask, taskID)
	var i Mount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.N,
		&i.Path,
		&i.State,
		&i.TaskID,
		&i.AcquiredAt,
		&i.ReleasedAt,
	)
	return i, err
}

const mounts = `-- name: Mounts :many
SELECT id, project_id, n, path, state, task_id, acquired_at, released_at FROM mounts WHERE project_id = ? ORDER BY n
`

func (q *Queries) Mounts(ctx context.Context, projectID int64) ([]Mount, error) {
	rows, err := q.db.QueryContext(ctx, mounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mount{}
	for rows.Next() {
		var i Mount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.N,
			&i.Path,
			&i.State,
			&i.TaskID,
			&i.AcquiredAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveProject = `-- name: MoveProject :exec
UPDATE projects SET root = ?, default_branch = ?, status = 'active', last_activity_at = ? WHERE id = ?
`

type MoveProjectParams struct {
	Root           string
	DefaultBranch  string
	LastActivityAt int64
	ID             int64
}

func (q *Queries) MoveProject(ctx context.Context, arg MoveProjectParams) error {
	_, err := q.db.ExecContext(ctx, moveProject,
		arg.Root,
		arg.DefaultBranch,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}

const nextMountNumber = `-- name: NextMountNumber :one
SELECT COALESCE(MAX(n), 0) + 1 FROM mounts WHERE project_id = ?
`

func (q *Queries) NextMountNumber(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMountNumber, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextTaskSeq = `-- name: NextTaskSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM tasks WHERE project_id = ?
`

func (q *Queries) NextTaskSeq(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTaskSeq, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const notices = `-- name: Notices :many
SELECT id, project_id, COALESCE(task_id, 0) AS task_id, kind, summary, data_json,
    created_at, COALESCE(delivered_at, 0) AS delivered_at, COALESCE(acked_at, 0) AS acked_at
FROM notices WHERE project_id = ? ORDER BY id
`

type NoticesRow struct {
	ID          int64
	ProjectID   int64
	TaskID      int64
	Kind        string
	Summary     string
	DataJson    string
	CreatedAt   int64
	DeliveredAt int64
	AckedAt     int64
}

func (q *Queries) Notices(ctx context.Context, projectID int64) ([]NoticesRow, error) {
	rows, err := q.db.QueryContext(ctx, notices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoticesRow{}
	for rows.Next() {
		var i NoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Kind,
			&i.Summary,
			&i.DataJson,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestQueuedMessage = `-- name: OldestQueuedMessage :one
SELECT id, task_id, body, created_at, COALESCE(delivered_at, 0) AS delivered_at, status
FROM messages WHERE task_id = ? AND status = 'queued' ORDER BY created_at, id LIMIT 1
`

type OldestQueuedMessageRow struct {
	ID          int64
	TaskID      int64
	Body        string
	CreatedAt   int64
	DeliveredAt int64
	Status      string
}

func (q *Queries) OldestQueuedMessage(ctx context.Context, taskID int64) (OldestQueuedMessageRow, error) {
	row := q.db.QueryRowContext(ctx, oldestQueuedMessage, taskID)
	var i OldestQueuedMessageRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Body,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.Status,
	)
	return i, err
}

const openNotices = `-- name: OpenNotices :many
SELECT id, project_id, COALESCE(task_id, 0) AS task_id, kind, summary, data_json,
    created_at, COALESCE(delivered_at, 0) AS delivered_at, COALESCE(acked_at, 0) AS acked_at
FROM notices WHERE project_id = ? AND acked_at IS NULL ORDER BY id
`

type OpenNoticesRow struct {
	ID          int64
	ProjectID   int64
	TaskID      int64
	Kind        string
	Summary     string
	DataJson    string
	CreatedAt   int64
	DeliveredAt int64
	AckedAt     int64
}

func (q *Queries) OpenNotices(ctx context.Context, projectID int64) ([]OpenNoticesRow, error) {
	rows, err := q.db.QueryContext(ctx, openNotices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenNoticesRow{}
	for rows.Next() {
		var i OpenNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Kind,
			&i.Summary,
			&i.DataJson,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pRBodyMarkerByTaskRepo = `-- name: PRBodyMarkerByTaskRepo :one
SELECT pr_url, marker_token FROM pr_body_markers WHERE task_id = ? AND repo = ?
`

type PRBodyMarkerByTaskRepoParams struct {
	TaskID int64
	Repo   string
}

type PRBodyMarkerByTaskRepoRow struct {
	PrUrl       string
	MarkerToken string
}

func (q *Queries) PRBodyMarkerByTaskRepo(ctx context.Context, arg PRBodyMarkerByTaskRepoParams) (PRBodyMarkerByTaskRepoRow, error) {
	row := q.db.QueryRowContext(ctx, pRBodyMarkerByTaskRepo, arg.TaskID, arg.Repo)
	var i PRBodyMarkerByTaskRepoRow
	err := row.Scan(&i.PrUrl, &i.MarkerToken)
	return i, err
}

const pRBodyMarkersByTask = `-- name: PRBodyMarkersByTask :many
SELECT task_id, repo, pr_url, marker_token, updated_at FROM pr_body_markers
WHERE task_id = ? ORDER BY repo
`

func (q *Queries) PRBodyMarkersByTask(ctx context.Context, taskID int64) ([]PrBodyMarker, error) {
	rows, err := q.db.QueryContext(ctx, pRBodyMarkersByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrBodyMarker{}
	for rows.Next() {
		var i PrBodyMarker
		if err := rows.Scan(
			&i.TaskID,
			&i.Repo,
			&i.PrUrl,
			&i.MarkerToken,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectByID = `-- name: ProjectByID :one
SELECT id, name, root, default_branch, herdr_workspace_id, lead_pane_id, lead_label, lead_absent_since, status, created_at, last_activity_at, lead_launches, kind, down_at FROM projects WHERE id = ?
`

func (q *Queries) ProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Root,
		&i.DefaultBranch,
		&i.HerdrWorkspaceID,
		&i.LeadPaneID,
		&i.LeadLabel,
		&i.LeadAbsentSince,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.LeadLaunches,
		&i.Kind,
		&i.DownAt,
	)
	return i, err
}

const projectByLeadPane = `-- name: ProjectByLeadPane :one
SELECT id, name, root, default_branch, herdr_workspace_id, lead_pane_id, lead_label, lead_absent_since, status, created_at, last_activity_at, lead_launches, kind, down_at FROM projects WHERE lead_pane_id = ?
`

func (q *Queries) ProjectByLeadPane(ctx context.Context, leadPaneID string) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectByLeadPane, leadPaneID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Root,
		&i.DefaultBranch,
		&i.HerdrWorkspaceID,
		&i.LeadPaneID,
		&i.LeadLabel,
		&i.LeadAbsentSince,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.LeadLaunches,
		&i.Kind,
		&i.DownAt,
	)
	return i, err
}

const projectByName = `-- name: ProjectByName :one
SELECT id, name, root, default_branch, herdr_workspace_id, lead_pane_id, lead_label, lead_absent_since, status, created_at, last_activity_at, lead_launches, kind, down_at FROM projects WHERE name = ?
`

func (q *Queries) ProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Root,
		&i.DefaultBranch,
		&i.HerdrWorkspaceID,
		&i.LeadPaneID,
		&i.LeadLabel,
		&i.LeadAbsentSince,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.LeadLaunches,
		&i.Kind,
		&i.DownAt,
	)
	return i, err
}

const projectByRoot = `-- name: ProjectByRoot :one
SELECT id, name, root, default_branch, herdr_workspace_id, lead_pane_id, lead_label, lead_absent_since, status, created_at, last_activity_at, lead_launches, kind, down_at FROM projects WHERE root = ?
`

func (q *Queries) ProjectByRoot(ctx context.Context, root string) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectByRoot, root)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Root,
		&i.DefaultBranch,
		&i.HerdrWorkspaceID,
		&i.LeadPaneID,
		&i.LeadLabel,
		&i.LeadAbsentSince,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.LeadLaunches,
		&i.Kind,
		&i.DownAt,
	)
	return i, err
}

const projects = `-- name: Projects :many
SELECT id, name, root, default_branch, herdr_workspace_id, lead_pane_id, lead_label, lead_absent_since, status, created_at, last_activity_at, lead_launches, kind, down_at FROM projects ORDER BY name
`

func (q *Queries) Projects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, projects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Root,
			&i.DefaultBranch,
			&i.HerdrWorkspaceID,
			&i.LeadPaneID,
			&i.LeadLabel,
			&i.LeadAbsentSince,
			&i.Status,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.LeadLaunches,
			&i.Kind,
			&i.DownAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEvents = `-- name: PruneEvents :exec
DELETE FROM events WHERE received_at < ?
`

func (q *Queries) PruneEvents(ctx context.Context, receivedAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneEvents, receivedAt)
	return err
}

const queueMessage = `-- name: QueueMessage :execresult
INSERT INTO messages(task_id, body, created_at, status) VALUES (?, ?, ?, 'queued')
`

type QueueMessageParams struct {
	TaskID    int64
	Body      string
	CreatedAt int64
}

func (q *Queries) QueueMessage(ctx context.Context, arg QueueMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, queueMessage, arg.TaskID, arg.Body, arg.CreatedAt)
}

const recordNoticeNotification = `-- name: RecordNoticeNotification :exec
INSERT INTO notice_notifications(project_id, notified_at) VALUES (?, ?)
ON CONFLICT(project_id) DO UPDATE SET notified_at = excluded.notified_at
`

type RecordNoticeNotificationParams struct {
	ProjectID  int64
	NotifiedAt int64
}

func (q *Queries) RecordNoticeNotification(ctx context.Context, arg RecordNoticeNotificationParams) error {
	_, err := q.db.ExecContext(ctx, recordNoticeNotification, arg.ProjectID, arg.NotifiedAt)
	return err
}

const refreshLeadStartClaim = `-- name: RefreshLeadStartClaim :execresult
UPDATE lead_start_claims SET claimed_at = ? WHERE project_id = ? AND claimed_at <= ?
`

type RefreshLeadStartClaimParams struct {
	ClaimedAt   int64
	ProjectID   int64
	ClaimedAt_2 int64
}

func (q *Queries) RefreshLeadStartClaim(ctx context.Context, arg RefreshLeadStartClaimParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, refreshLeadStartClaim, arg.ClaimedAt, arg.ProjectID, arg.ClaimedAt_2)
}

const releaseLeadStart = `-- name: ReleaseLeadStart :exec
DELETE FROM lead_start_claims WHERE project_id = ?
`

func (q *Queries) ReleaseLeadStart(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, releaseLeadStart, projectID)
	return err
}

const releaseMount = `-- name: ReleaseMount :exec
UPDATE mounts SET state = 'idle', task_id = NULL, released_at = ? WHERE id = ? AND task_id = ? AND state = 'held'
`

type ReleaseMountParams struct {
	ReleasedAt int64
	ID         int64
	TaskID     sql.NullInt64
}

func (q *Queries) ReleaseMount(ctx context.Context, arg ReleaseMountParams) error {
	_, err := q.db.ExecContext(ctx, releaseMount, arg.ReleasedAt, arg.ID, arg.TaskID)
	return err
}

const resetProgress = `-- name: ResetProgress :exec
UPDATE tasks SET last_output_hash = '', last_worktree_hash = '', last_progress_at = 0, updated_at = ?
WHERE id = ? AND state = 'working'
`

type ResetProgressParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ResetProgress(ctx context.Context, arg ResetProgressParams) error {
	_, err := q.db.ExecContext(ctx, resetProgress, arg.UpdatedAt, arg.ID)
	return err
}

const resetTaskProgress = `-- name: ResetTaskProgress :exec
UPDATE tasks SET last_output_hash = '', last_worktree_hash = '', last_progress_at = 0, idle_since = 0, updated_at = ?
WHERE id = ? AND state = 'working'
`

type ResetTaskProgressParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ResetTaskProgress(ctx context.Context, arg ResetTaskProgressParams) error {
	_, err := q.db.ExecContext(ctx, resetTaskProgress, arg.UpdatedAt, arg.ID)
	return err
}

const setProjectLead = `-- name: SetProjectLead :exec
UPDATE projects SET herdr_workspace_id = ?, lead_pane_id = ?, lead_label = ?,
    lead_absent_since = 0, down_at = 0, status = 'active', last_activity_at = ? WHERE id = ?
`

type SetProjectLeadParams struct {
	HerdrWorkspaceID string
	LeadPaneID       string
	LeadLabel        string
	LastActivityAt   int64
	ID               int64
}

func (q *Queries) SetProjectLead(ctx context.Context, arg SetProjectLeadParams) error {
	_, err := q.db.ExecContext(ctx, setProjectLead,
		arg.HerdrWorkspaceID,
		arg.LeadPaneID,
		arg.LeadLabel,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}

const setTaskGatedSHA = `-- name: SetTaskGatedSHA :exec
UPDATE tasks SET gated_sha = ?, updated_at = ? WHERE id = ? AND state = 'done'
`

type SetTaskGatedSHAParams struct {
	GatedSha  string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetTaskGatedSHA(ctx context.Context, arg SetTaskGatedSHAParams) error {
	_, err := q.db.ExecContext(ctx, setTaskGatedSHA, arg.GatedSha, arg.UpdatedAt, arg.ID)
	return err
}

const stallTasks = `-- name: StallTasks :many
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE project_id = ? AND state IN ('working', 'stalled') ORDER BY seq
`

func (q *Queries) StallTasks(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, stallTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.ReviewsTaskID,
			&i.Title,
			&i.State,
			&i.Profile,
			&i.DispatchRule,
			&i.LandingMode,
			&i.AutonomyReview,
			&i.AutonomyLand,
			&i.Branch,
			&i.BaseRef,
			&i.WorktreePath,
			&i.HerdrWorkspaceID,
			&i.PaneID,
			&i.PaneLabel,
			&i.AgentName,
			&i.AgentSession,
			&i.PrUrl,
			&i.LandedRef,
			&i.LastOutputHash,
			&i.LastWorktreeHash,
			&i.LastProgressAt,
			&i.AgentAbsentSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MountID,
			&i.Launches,
			&i.GatedSha,
			&i.AgentServerStartedAt,
			&i.IdleSince,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const task = `-- name: Task :one
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE project_id = ?1 AND (
    CAST('t' || seq AS TEXT) = CAST(?2 AS TEXT)
)
`

type TaskParams struct {
	ProjectID  int64
	Identifier string
}

func (q *Queries) Task(ctx context.Context, arg TaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, task, arg.ProjectID, arg.Identifier)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Type,
		&i.ReviewsTaskID,
		&i.Title,
		&i.State,
		&i.Profile,
		&i.DispatchRule,
		&i.LandingMode,
		&i.AutonomyReview,
		&i.AutonomyLand,
		&i.Branch,
		&i.BaseRef,
		&i.WorktreePath,
		&i.HerdrWorkspaceID,
		&i.PaneID,
		&i.PaneLabel,
		&i.AgentName,
		&i.AgentSession,
		&i.PrUrl,
		&i.LandedRef,
		&i.LastOutputHash,
		&i.LastWorktreeHash,
		&i.LastProgressAt,
		&i.AgentAbsentSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MountID,
		&i.Launches,
		&i.GatedSha,
		&i.AgentServerStartedAt,
		&i.IdleSince,
		&i.ShortName,
	)
	return i, err
}

const taskByID = `-- name: TaskByID :one
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE project_id = ? AND id = ?
`

type TaskByIDParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) TaskByID(ctx context.Context, arg TaskByIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskByID, arg.ProjectID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Type,
		&i.ReviewsTaskID,
		&i.Title,
		&i.State,
		&i.Profile,
		&i.DispatchRule,
		&i.LandingMode,
		&i.AutonomyReview,
		&i.AutonomyLand,
		&i.Branch,
		&i.BaseRef,
		&i.WorktreePath,
		&i.HerdrWorkspaceID,
		&i.PaneID,
		&i.PaneLabel,
		&i.AgentName,
		&i.AgentSession,
		&i.PrUrl,
		&i.LandedRef,
		&i.LastOutputHash,
		&i.LastWorktreeHash,
		&i.LastProgressAt,
		&i.AgentAbsentSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MountID,
		&i.Launches,
		&i.GatedSha,
		&i.AgentServerStartedAt,
		&i.IdleSince,
		&i.ShortName,
	)
	return i, err
}

const taskByPane = `-- name: TaskByPane :one
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE pane_id = ? AND state != 'torn-down' ORDER BY id DESC LIMIT 1
`

func (q *Queries) TaskByPane(ctx context.Context, paneID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskByPane, paneID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Type,
		&i.ReviewsTaskID,
		&i.Title,
		&i.State,
		&i.Profile,
		&i.DispatchRule,
		&i.LandingMode,
		&i.AutonomyReview,
		&i.AutonomyLand,
		&i.Branch,
		&i.BaseRef,
		&i.WorktreePath,
		&i.HerdrWorkspaceID,
		&i.PaneID,
		&i.PaneLabel,
		&i.AgentName,
		&i.AgentSession,
		&i.PrUrl,
		&i.LandedRef,
		&i.LastOutputHash,
		&i.LastWorktreeHash,
		&i.LastProgressAt,
		&i.AgentAbsentSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MountID,
		&i.Launches,
		&i.GatedSha,
		&i.AgentServerStartedAt,
		&i.IdleSince,
		&i.ShortName,
	)
	return i, err
}

const taskByWorktree = `-- name: TaskByWorktree :one
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE worktree_path = ? AND state != 'torn-down' ORDER BY id DESC LIMIT 1
`

func (q *Queries) TaskByWorktree(ctx context.Context, worktreePath string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskByWorktree, worktreePath)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Type,
		&i.ReviewsTaskID,
		&i.Title,
		&i.State,
		&i.Profile,
		&i.DispatchRule,
		&i.LandingMode,
		&i.AutonomyReview,
		&i.AutonomyLand,
		&i.Branch,
		&i.BaseRef,
		&i.WorktreePath,
		&i.HerdrWorkspaceID,
		&i.PaneID,
		&i.PaneLabel,
		&i.AgentName,
		&i.AgentSession,
		&i.PrUrl,
		&i.LandedRef,
		&i.LastOutputHash,
		&i.LastWorktreeHash,
		&i.LastProgressAt,
		&i.AgentAbsentSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MountID,
		&i.Launches,
		&i.GatedSha,
		&i.AgentServerStartedAt,
		&i.IdleSince,
		&i.ShortName,
	)
	return i, err
}

const taskGatedSHA = `-- name: TaskGatedSHA :one
SELECT gated_sha FROM tasks WHERE id = ?
`

func (q *Queries) TaskGatedSHA(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, taskGatedSHA, id)
	var gated_sha string
	err := row.Scan(&gated_sha)
	return gated_sha, err
}

const taskSignals = `-- name: TaskSignals :many
SELECT id, task_id, verb, note, data_json, at FROM signals
WHERE task_id = ? ORDER BY id DESC LIMIT ?
`

type TaskSignalsParams struct {
	TaskID int64
	Limit  int64
}

func (q *Queries) TaskSignals(ctx context.Context, arg TaskSignalsParams) ([]Signal, error) {
	rows, err := q.db.QueryContext(ctx, taskSignals, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Verb,
			&i.Note,
			&i.DataJson,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskTransitions = `-- name: TaskTransitions :many
SELECT id, task_id, from_state, to_state, source, note, at FROM transitions
WHERE task_id = ? ORDER BY id DESC LIMIT ?
`

type TaskTransitionsParams struct {
	TaskID int64
	Limit  int64
}

func (q *Queries) TaskTransitions(ctx context.Context, arg TaskTransitionsParams) ([]Transition, error) {
	rows, err := q.db.QueryContext(ctx, taskTransitions, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transition{}
	for rows.Next() {
		var i Transition
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromState,
			&i.ToState,
			&i.Source,
			&i.Note,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasks = `-- name: Tasks :many
SELECT id, project_id, seq, type, reviews_task_id, title, state, profile, dispatch_rule, landing_mode, autonomy_review, autonomy_land, branch, base_ref, worktree_path, herdr_workspace_id, pane_id, pane_label, agent_name, agent_session, pr_url, landed_ref, last_output_hash, last_worktree_hash, last_progress_at, agent_absent_since, created_at, updated_at, mount_id, launches, gated_sha, agent_server_started_at, idle_since, short_name FROM tasks
WHERE project_id = ? AND state NOT IN ('landed', 'reported', 'torn-down') ORDER BY seq
`

func (q *Queries) Tasks(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, tasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.ReviewsTaskID,
			&i.Title,
			&i.State,
			&i.Profile,
			&i.DispatchRule,
			&i.LandingMode,
			&i.AutonomyReview,
			&i.AutonomyLand,
			&i.Branch,
			&i.BaseRef,
			&i.WorktreePath,
			&i.HerdrWorkspaceID,
			&i.PaneID,
			&i.PaneLabel,
			&i.AgentName,
			&i.AgentSession,
			&i.PrUrl,
			&i.LandedRef,
			&i.LastOutputHash,
			&i.LastWorktreeHash,
			&i.LastProgressAt,
			&i.AgentAbsentSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MountID,
			&i.Launches,
			&i.GatedSha,
			&i.AgentServerStartedAt,
			&i.IdleSince,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProjectForTask = `-- name: TouchProjectForTask :exec
UPDATE projects SET last_activity_at = ? WHERE projects.id = (SELECT project_id FROM tasks WHERE tasks.id = ?)
`

type TouchProjectForTaskParams struct {
	LastActivityAt int64
	ID             int64
}

func (q *Queries) TouchProjectForTask(ctx context.Context, arg TouchProjectForTaskParams) error {
	_, err := q.db.ExecContext(ctx, touchProjectForTask, arg.LastActivityAt, arg.ID)
	return err
}

const undeliveredNotices = `-- name: UndeliveredNotices :many
SELECT id, project_id, COALESCE(task_id, 0) AS task_id, kind, summary, data_json,
    created_at, 0 AS delivered_at, 0 AS acked_at
FROM notices WHERE project_id = ? AND delivered_at IS NULL AND acked_at IS NULL AND claim_token = '' ORDER BY id
`

type UndeliveredNoticesRow struct {
	ID          int64
	ProjectID   int64
	TaskID      int64
	Kind        string
	Summary     string
	DataJson    string
	CreatedAt   int64
	DeliveredAt int64
	AckedAt     int64
}

func (q *Queries) UndeliveredNotices(ctx context.Context, projectID int64) ([]UndeliveredNoticesRow, error) {
	rows, err := q.db.QueryContext(ctx, undeliveredNotices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UndeliveredNoticesRow{}
	for rows.Next() {
		var i UndeliveredNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Kind,
			&i.Summary,
			&i.DataJson,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgress = `-- name: UpdateProgress :exec
UPDATE tasks SET last_output_hash = ?, last_worktree_hash = ?, last_progress_at = ?, updated_at = ?
WHERE id = ? AND state = 'working'
`

type UpdateProgressParams struct {
	LastOutputHash   string
	LastWorktreeHash string
	LastProgressAt   int64
	UpdatedAt        int64
	ID               int64
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateProgress,
		arg.LastOutputHash,
		arg.LastWorktreeHash,
		arg.LastProgressAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProjectObservation = `-- name: UpdateProjectObservation :exec
UPDATE projects SET lead_pane_id = ?, herdr_workspace_id = ?, lead_absent_since = ? WHERE id = ?
`

type UpdateProjectObservationParams struct {
	LeadPaneID       string
	HerdrWorkspaceID string
	LeadAbsentSince  int64
	ID               int64
}

func (q *Queries) UpdateProjectObservation(ctx context.Context, arg UpdateProjectObservationParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectObservation,
		arg.LeadPaneID,
		arg.HerdrWorkspaceID,
		arg.LeadAbsentSince,
		arg.ID,
	)
	return err
}

const updateTaskLanding = `-- name: UpdateTaskLanding :exec
UPDATE tasks SET pr_url = ?, landed_ref = ?, updated_at = ? WHERE id = ?
`

type UpdateTaskLandingParams struct {
	PrUrl     string
	LandedRef string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateTaskLanding(ctx context.Context, arg UpdateTaskLandingParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskLanding,
		arg.PrUrl,
		arg.LandedRef,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTaskLaunch = `-- name: UpdateTaskLaunch :exec
UPDATE tasks SET worktree_path = ?, herdr_workspace_id = ?, pane_id = ?, pane_label = ?,
    agent_name = ?, updated_at = ? WHERE id = ?
`

type UpdateTaskLaunchParams struct {
	WorktreePath     string
	HerdrWorkspaceID string
	PaneID           string
	PaneLabel        string
	AgentName        string
	UpdatedAt        int64
	ID               int64
}

func (q *Queries) UpdateTaskLaunch(ctx context.Context, arg UpdateTaskLaunchParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskLaunch,
		arg.WorktreePath,
		arg.HerdrWorkspaceID,
		arg.PaneID,
		arg.PaneLabel,
		arg.AgentName,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTaskMount = `-- name: UpdateTaskMount :exec
UPDATE tasks SET mount_id = ?, worktree_path = ?, updated_at = ? WHERE id = ?
`

type UpdateTaskMountParams struct {
	MountID      sql.NullInt64
	WorktreePath string
	UpdatedAt    int64
	ID           int64
}

func (q *Queries) UpdateTaskMount(ctx context.Context, arg UpdateTaskMountParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskMount,
		arg.MountID,
		arg.WorktreePath,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTaskObservation = `-- name: UpdateTaskObservation :exec
UPDATE tasks SET pane_id = ?, herdr_workspace_id = ?, agent_session = ?, agent_absent_since = ?, agent_server_started_at = ?, idle_since = ?,
    updated_at = ? WHERE id = ?
`

type UpdateTaskObservationParams struct {
	PaneID               string
	HerdrWorkspaceID     string
	AgentSession         string
	AgentAbsentSince     int64
	AgentServerStartedAt string
	IdleSince            int64
	UpdatedAt            int64
	ID                   int64
}

func (q *Queries) UpdateTaskObservation(ctx context.Context, arg UpdateTaskObservationParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskObservation,
		arg.PaneID,
		arg.HerdrWorkspaceID,
		arg.AgentSession,
		arg.AgentAbsentSince,
		arg.AgentServerStartedAt,
		arg.IdleSince,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTaskState = `-- name: UpdateTaskState :execresult
UPDATE tasks SET state = ?, updated_at = ?,
    last_output_hash = CASE WHEN ? = 'working' THEN '' ELSE last_output_hash END,
    last_worktree_hash = CASE WHEN ? = 'working' THEN '' ELSE last_worktree_hash END,
    last_progress_at = CASE WHEN ? = 'working' THEN 0 ELSE last_progress_at END
WHERE id = ? AND state = ?
`

type UpdateTaskStateParams struct {
	State     string
	UpdatedAt int64
	Column3   interface{}
	Column4   interface{}
	Column5   interface{}
	ID        int64
	State_2   string
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskState,
		arg.State,
		arg.UpdatedAt,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.ID,
		arg.State_2,
	)
}

const updateTaskWorkspace = `-- name: UpdateTaskWorkspace :exec
UPDATE tasks SET herdr_workspace_id = ?, pane_id = ?, updated_at = ? WHERE id = ?
`

type UpdateTaskWorkspaceParams struct {
	HerdrWorkspaceID string
	PaneID           string
	UpdatedAt        int64
	ID               int64
}

func (q *Queries) UpdateTaskWorkspace(ctx context.Context, arg UpdateTaskWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskWorkspace,
		arg.HerdrWorkspaceID,
		arg.PaneID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertPRBodyMarker = `-- name: UpsertPRBodyMarker :exec
INSERT INTO pr_body_markers(task_id, repo, pr_url, marker_token, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(task_id, repo) DO UPDATE SET
    pr_url = excluded.pr_url,
    marker_token = excluded.marker_token,
    updated_at = excluded.updated_at
`

type UpsertPRBodyMarkerParams struct {
	TaskID      int64
	Repo        string
	PrUrl       string
	MarkerToken string
	UpdatedAt   int64
}

func (q *Queries) UpsertPRBodyMarker(ctx context.Context, arg UpsertPRBodyMarkerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPRBodyMarker,
		arg.TaskID,
		arg.Repo,
		arg.PrUrl,
		arg.MarkerToken,
		arg.UpdatedAt,
	)
	return err
}
