// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AckAllNotices(ctx context.Context, arg AckAllNoticesParams) (sql.Result, error)
	AckNotice(ctx context.Context, arg AckNoticeParams) (sql.Result, error)
	AcquireIdleMount(ctx context.Context, arg AcquireIdleMountParams) (sql.Result, error)
	ActiveWorkerCount(ctx context.Context, projectID int64) (int64, error)
	AllTasks(ctx context.Context, projectID int64) ([]Task, error)
	AllocateLeadLaunch(ctx context.Context, id int64) (int64, error)
	AllocateTaskLaunch(ctx context.Context, arg AllocateTaskLaunchParams) (int64, error)
	AllocateTaskSequence(ctx context.Context, projectID int64) (int64, error)
	BindPRBodyMarker(ctx context.Context, arg BindPRBodyMarkerParams) (sql.Result, error)
	BreakMount(ctx context.Context, arg BreakMountParams) error
	ClearDownProjectLead(ctx context.Context, id int64) error
	ClearGatedSHALandingToDone(ctx context.Context, id int64) error
	ClearProjectLead(ctx context.Context, id int64) error
	ClearTaskGatedSHA(ctx context.Context, arg ClearTaskGatedSHAParams) error
	ClearWorkspaceToken(ctx context.Context, projectID int64) error
	CountApproval(ctx context.Context, arg CountApprovalParams) (int64, error)
	DeleteMount(ctx context.Context, arg DeleteMountParams) (sql.Result, error)
	InsertApproval(ctx context.Context, arg InsertApprovalParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertLeadStartClaim(ctx context.Context, arg InsertLeadStartClaimParams) (sql.Result, error)
	InsertMount(ctx context.Context, arg InsertMountParams) (sql.Result, error)
	InsertNotice(ctx context.Context, arg InsertNoticeParams) (sql.Result, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error)
	InsertSignal(ctx context.Context, arg InsertSignalParams) (sql.Result, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (sql.Result, error)
	InsertTransition(ctx context.Context, arg InsertTransitionParams) error
	LastNoticeDelivery(ctx context.Context, projectID int64) (int64, error)
	LastNoticeNotification(ctx context.Context, projectID int64) (int64, error)
	LiveTasks(ctx context.Context, projectID int64) ([]Task, error)
	MarkMessageDelivered(ctx context.Context, arg MarkMessageDeliveredParams) error
	MarkNoticeDelivered(ctx context.Context, arg MarkNoticeDeliveredParams) error
	MarkProjectDown(ctx context.Context, arg MarkProjectDownParams) error
	MountByTask(ctx context.Context, taskID sql.NullInt64) (Mount, error)
	Mounts(ctx context.Context, projectID int64) ([]Mount, error)
	MoveProject(ctx context.Context, arg MoveProjectParams) error
	NextMountNumber(ctx context.Context, projectID int64) (int64, error)
	NextTaskSeq(ctx context.Context, projectID int64) (int64, error)
	Notices(ctx context.Context, projectID int64) ([]NoticesRow, error)
	OldestQueuedMessage(ctx context.Context, taskID int64) (OldestQueuedMessageRow, error)
	OpenNotices(ctx context.Context, projectID int64) ([]OpenNoticesRow, error)
	PRBodyMarkerByTaskRepo(ctx context.Context, arg PRBodyMarkerByTaskRepoParams) (PRBodyMarkerByTaskRepoRow, error)
	ProjectByID(ctx context.Context, id int64) (Project, error)
	ProjectByLeadPane(ctx context.Context, leadPaneID string) (Project, error)
	ProjectByName(ctx context.Context, name string) (Project, error)
	ProjectByRoot(ctx context.Context, root string) (Project, error)
	Projects(ctx context.Context) ([]Project, error)
	PruneEvents(ctx context.Context, receivedAt int64) error
	QueueMessage(ctx context.Context, arg QueueMessageParams) (sql.Result, error)
	RecordNoticeNotification(ctx context.Context, arg RecordNoticeNotificationParams) error
	RefreshLeadStartClaim(ctx context.Context, arg RefreshLeadStartClaimParams) (sql.Result, error)
	ReleaseLeadStart(ctx context.Context, projectID int64) error
	ReleaseMount(ctx context.Context, arg ReleaseMountParams) error
	ResetProgress(ctx context.Context, arg ResetProgressParams) error
	ResetTaskProgress(ctx context.Context, arg ResetTaskProgressParams) error
	SetProjectLead(ctx context.Context, arg SetProjectLeadParams) error
	SetTaskGatedSHA(ctx context.Context, arg SetTaskGatedSHAParams) error
	StallTasks(ctx context.Context, projectID int64) ([]Task, error)
	Task(ctx context.Context, arg TaskParams) (Task, error)
	TaskByID(ctx context.Context, arg TaskByIDParams) (Task, error)
	TaskByPane(ctx context.Context, paneID string) (Task, error)
	TaskByWorktree(ctx context.Context, worktreePath string) (Task, error)
	TaskGatedSHA(ctx context.Context, id int64) (string, error)
	TaskSignals(ctx context.Context, arg TaskSignalsParams) ([]Signal, error)
	TaskTransitions(ctx context.Context, arg TaskTransitionsParams) ([]Transition, error)
	Tasks(ctx context.Context, projectID int64) ([]Task, error)
	TouchProjectForTask(ctx context.Context, arg TouchProjectForTaskParams) error
	UndeliveredNotices(ctx context.Context, projectID int64) ([]UndeliveredNoticesRow, error)
	UpdateProgress(ctx context.Context, arg UpdateProgressParams) error
	UpdateProjectObservation(ctx context.Context, arg UpdateProjectObservationParams) error
	UpdateTaskLanding(ctx context.Context, arg UpdateTaskLandingParams) error
	UpdateTaskLaunch(ctx context.Context, arg UpdateTaskLaunchParams) error
	UpdateTaskMount(ctx context.Context, arg UpdateTaskMountParams) error
	UpdateTaskObservation(ctx context.Context, arg UpdateTaskObservationParams) error
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (sql.Result, error)
	UpdateTaskWorkspace(ctx context.Context, arg UpdateTaskWorkspaceParams) error
	UpsertPRBodyMarker(ctx context.Context, arg UpsertPRBodyMarkerParams) error
}

var _ Querier = (*Queries)(nil)
